const state={catalog:[],data:null,selected:[],bound:false,geo:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=v=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("es-AR",{maximumFractionDigits:2}).format(n):v??"—"};
const unique=(rows,key)=>[...new Set(rows.map(r=>String(r[key]??"")).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"es",{numeric:true}));
const topic=v=>String(v||"").split("-").map(x=>x?x[0].toUpperCase()+x.slice(1):"").join(" ");
function fill(select,values,all=false){select.innerHTML=(all?'<option value="">Todos</option>':"")+values.map(v=>'<option value="'+esc(v.value??v)+'">'+esc(v.label??v)+'</option>').join("");select.value=all?"":String(values[0]?.value??values[0]??"")}
function fillBoards(){const grouped=new Map();state.catalog.forEach(x=>{const key=topic(x.topic)||"Otros";if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(x)});$("board").innerHTML=[...grouped].map(([name,items])=>'<optgroup label="'+esc(name)+'">'+items.map(x=>'<option value="'+esc(x.slug)+'">'+esc(x.name)+' · '+esc(x.family)+'</option>').join("")+'</optgroup>').join("")}
function indicatorName(id){return state.data?.indicators.find(x=>String(x.id)===String(id))?.name||id}
function bind(){if(state.bound)return;state.bound=true;$("board").addEventListener("change",()=>loadBoard($("board").value));$("indicator").addEventListener("change",rebuildFilters);["type","year"].forEach(id=>$(id).addEventListener("change",render));$("reset").onclick=()=>{$("indicator").selectedIndex=0;rebuildFilters()};$("download").onclick=download}
async function bootstrap(){bind();const[r,g]=await Promise.all([fetch("catalog.json"),fetch("provincias.geojson")]);if(!r.ok)throw new Error("HTTP "+r.status);state.catalog=(await r.json()).dashboards;state.geo=g.ok?await g.json():null;fillBoards();const requested=new URLSearchParams(location.search).get("tablero"),selected=state.catalog.some(x=>x.slug===requested)?requested:state.catalog[0]?.slug;$("board").value=selected;await loadBoard(selected)}
async function loadBoard(slug){const item=state.catalog.find(x=>x.slug===slug);if(!item)return;$("message").hidden=false;$("message").textContent="Cargando "+item.name+"…";$("dashboard").hidden=true;const r=await fetch(item.data);if(!r.ok)throw new Error("HTTP "+r.status);setup(await r.json());const url=new URL(location.href);url.searchParams.set("tablero",slug);history.replaceState(null,"",url)}
function setup(data){state.data=data;$("title").textContent=data.dashboard.name||"Tablero LADEFE";$("description").textContent=data.dashboard.description||"";$("updated").textContent=(data.dashboard.lastDataLoad||"Sin informar")+" · Familia "+data.family;fill($("indicator"),data.indicators.map(x=>({value:x.id,label:x.name})));rebuildFilters()}
function base(){const id=$("indicator").value;return state.data.rows.filter(r=>String(r.indicatorId)===id)}
function rebuildFilters(){const rows=base();fill($("type"),unique(rows,"type"),true);fill($("year"),unique(rows,"year").sort((a,b)=>Number(b)-Number(a)),true);render()}
function filtered(){return base().filter(r=>(!$("type").value||String(r.type)===$("type").value)&&(!$("year").value||String(r.year)===$("year").value))}
function companion(kind){const own=base().filter(r=>r.type===kind);if(own.length)return{rows:own,id:$("indicator").value};const groups=new Set(base().map(r=>String(r.groupId||"")).filter(Boolean));const related=state.data.rows.filter(r=>r.type===kind&&groups.has(String(r.groupId||"")));if(related.length){const counts=new Map();related.forEach(r=>counts.set(String(r.indicatorId),(counts.get(String(r.indicatorId))||0)+1));const id=[...counts].sort((a,b)=>b[1]-a[1])[0][0];return{rows:related.filter(r=>String(r.indicatorId)===id),id}}return{rows:[],id:null}}
function render(){const rows=filtered();state.selected=rows;$("message").hidden=true;$("dashboard").hidden=false;$("records").textContent=rows.length+" registros visibles";const years=unique(base(),"year").map(Number).filter(Number.isFinite);$("range").textContent=years.length?Math.min(...years)+"–"+Math.max(...years):"—";const latest=$("year").value||(years.length?String(Math.max(...years)):""),latestRows=rows.filter(r=>String(r.year)===latest);$("territories").textContent=unique(latestRows,"geoName").length;const national=latestRows.find(r=>/total|argentina|nacional|país/i.test((r.geoName||"")+" "+[r.opening,r.mode1,r.mode2].filter(Boolean).join(" ")));$("national").textContent=national?fmt(national.value):"—";$("nationalNote").textContent=national?(national.mode2||national.mode1||"Año "+latest):"Sin agregado nacional";drawLine();drawMap();drawRanking(latestRows);drawTable(rows)}
function periodRank(r){const y=Number(r.year)||0,m=String(r.month||"").toUpperCase(),n=Number((m.match(/\d+/)||[])[0]||0),factor=m.startsWith("T")||m.startsWith("Q")?3:m.startsWith("S")?6:1;return y*12+(n?n*factor:0)}
function periodLabel(r){return[r.year,r.month].filter(v=>v!==null&&v!=="").join(" ")}
function seriesLabel(r){return String(r.mode2||r.mode1||r.opening||"Serie")}
function drawLine(){const svg=$("lineChart"),source=companion("SERIE_TEMPORAL");svg.innerHTML="";$("seriesLabel").textContent=source.id?indicatorName(source.id):"Sin vista temporal";if(!source.rows.length){svg.innerHTML='<text x="380" y="165" text-anchor="middle" class="tick">Este indicador no tiene una vista temporal asociada</text>';return}const categories=[...new Map(source.rows.slice().sort((a,b)=>periodRank(a)-periodRank(b)).map(r=>[periodLabel(r),r])).entries()].map(([label,row])=>({label,rank:periodRank(row)})),index=new Map(categories.map((x,i)=>[x.label,i])),groups=new Map();source.rows.forEach(r=>{const name=seriesLabel(r),v=Number(r.value),label=periodLabel(r);if(!Number.isFinite(v)||!index.has(label))return;if(!groups.has(name))groups.set(name,new Map());const m=groups.get(name),arr=m.get(label)||[];arr.push(v);m.set(label,arr)});const lines=[...groups].slice(0,6).map(([name,m])=>({name,points:[...m].map(([label,a])=>({i:index.get(label),label,value:a.reduce((x,y)=>x+y,0)/a.length})).sort((a,b)=>a.i-b.i)})),all=lines.flatMap(x=>x.points.map(p=>p.value));if(!all.length)return;const W=760,H=330,p={l:58,r:18,t:48,b:45},lo=Math.min(...all),hi=Math.max(...all),sx=i=>p.l+i/(Math.max(1,categories.length-1))*(W-p.l-p.r),sy=v=>p.t+(hi-v)/(hi-lo||1)*(H-p.t-p.b),colors=["#00a6a6","#1769aa","#e07a3f","#7654a8","#2d8a57","#c14f6b"];for(let i=0;i<5;i++){const y=p.t+i*(H-p.t-p.b)/4,val=hi-i*(hi-lo)/4;svg.insertAdjacentHTML("beforeend",'<line class="gridline" x1="'+p.l+'" y1="'+y+'" x2="'+(W-p.r)+'" y2="'+y+'"/><text class="tick" x="'+(p.l-8)+'" y="'+(y+4)+'" text-anchor="end">'+esc(fmt(val))+'</text>')}lines.forEach((line,k)=>{const color=colors[k%colors.length];svg.insertAdjacentHTML("beforeend",'<path class="series" stroke="'+color+'" d="'+line.points.map((q,i)=>(i?"L":"M")+sx(q.i)+","+sy(q.value)).join(" ")+'"/>');line.points.forEach(q=>svg.insertAdjacentHTML("beforeend",'<circle cx="'+sx(q.i)+'" cy="'+sy(q.value)+'" r="3" fill="#fff" stroke="'+color+'" stroke-width="2"><title>'+esc(line.name+" · "+q.label+": "+fmt(q.value))+'</title></circle>'));const lx=p.l+(k%3)*225,ly=15+Math.floor(k/3)*18;svg.insertAdjacentHTML("beforeend",'<line x1="'+lx+'" y1="'+ly+'" x2="'+(lx+18)+'" y2="'+ly+'" stroke="'+color+'" stroke-width="3"/><text class="tick" x="'+(lx+24)+'" y="'+(ly+4)+'">'+esc(line.name.slice(0,27))+'</text>')});const step=Math.max(1,Math.ceil(categories.length/7));categories.forEach((c,i)=>{if(i%step===0||i===categories.length-1)svg.insertAdjacentHTML("beforeend",'<text class="tick" x="'+sx(i)+'" y="'+(H-16)+'" text-anchor="middle">'+esc(c.label)+'</text>')})}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z]/g,"")}
function provinceKey(v){const n=norm(v);if(n.includes("CIUDADAUTONOMA")||n==="CABA"||n.includes("CAPITALFEDERAL"))return"CABA";if(n.includes("TIERRADELFUEGO"))return"TIERRADELFUEGO";return n.replace(/^PROVINCIADE/,"")}
function featureName(f){const p=f.properties||{};return p.nam||p.nombre||p.NAME_1||p.fna||p.gna||"Provincia"}
function rings(g){if(!g)return[];if(g.type==="Polygon")return g.coordinates;if(g.type==="MultiPolygon")return g.coordinates.flat();return[]}
function drawMap(){const svg=$("mapChart"),source=companion("MAPA");svg.innerHTML="";if(!state.geo){svg.innerHTML='<text x="210" y="235" text-anchor="middle" class="tick">Geometría no disponible</text>';return}if(!source.rows.length){$("rankingYear").textContent="Sin vista territorial asociada";paintMap(new Map(),svg);return}const years=unique(source.rows,"year").map(Number).filter(Number.isFinite),requested=Number($("year").value),year=years.includes(requested)?requested:Math.max(...years),rows=source.rows.filter(r=>Number(r.year)===year);$("rankingYear").textContent="Año "+year+" · "+indicatorName(source.id);const agg=new Map();rows.forEach(r=>{const v=Number(r.value),k=provinceKey(r.geoName);if(Number.isFinite(v)&&k){if(!agg.has(k))agg.set(k,[]);agg.get(k).push(v)}});paintMap(agg,svg)}
function paintMap(agg,svg){const values=[...agg.values()].map(a=>a.reduce((x,y)=>x+y,0)/a.length),lo=Math.min(...values),hi=Math.max(...values),color=v=>{if(!Number.isFinite(v))return"#e6ecef";const t=(v-lo)/(hi-lo||1),a=[217,238,240],b=[0,166,166],c=[11,36,63],mix=(x,y,z)=>Math.round(x+(y-x)*z),rgb=t<.55?a.map((x,i)=>mix(x,b[i],t/.55)):b.map((x,i)=>mix(x,c[i],(t-.55)/.45));return"rgb("+rgb.join(",")+")"},project=([x,y])=>[(x+74)/21*360+30,(y+21)/-34*430+18];for(const f of state.geo.features||[]){const name=featureName(f),key=provinceKey(name),arr=agg.get(key)||[],value=arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:NaN;let d="";for(const ring of rings(f.geometry)){const points=ring.filter(([x,y])=>x>=-74.5&&x<=-52.5&&y>=-56&&y<=-20).map(project);if(points.length>2)d+=points.map((p,i)=>(i?"L":"M")+p[0].toFixed(1)+","+p[1].toFixed(1)).join("")+"Z"}if(d)svg.insertAdjacentHTML("beforeend",'<path class="province" d="'+d+'" fill="'+color(value)+'"><title>'+esc(name+": "+(Number.isFinite(value)?fmt(value):"sin dato"))+'</title></path>')}if(!values.length)svg.insertAdjacentHTML("beforeend",'<rect x="65" y="205" width="290" height="56" rx="8" fill="#fff" opacity=".92"/><text x="210" y="227" text-anchor="middle" class="tick">Este indicador no contiene datos provinciales.</text><text x="210" y="246" text-anchor="middle" class="tick">Probá otro indicador del tablero.</text>')}
function drawRanking(rows){const geoRows=rows.filter(r=>r.geoName);const agg=new Map();geoRows.forEach(r=>{const n=r.geoName,v=Number(r.value);if(Number.isFinite(v)){if(!agg.has(n))agg.set(n,[]);agg.get(n).push(v)}});const vals=[...agg].map(([name,v])=>({name,value:v.reduce((a,b)=>a+b,0)/v.length})).sort((a,b)=>b.value-a.value).slice(0,24),max=Math.max(...vals.map(x=>Math.abs(x.value)),1);$("ranking").innerHTML=vals.length?vals.map(x=>'<div class="rank"><span class="rank-name" title="'+esc(x.name)+'">'+esc(x.name)+'</span><span class="bar"><i style="width:'+Math.max(2,Math.abs(x.value)/max*100)+'%"></i></span><span class="rank-value">'+esc(fmt(x.value))+'</span></div>').join(""):""}
function drawTable(rows){$("rows").innerHTML=rows.slice(0,250).map(r=>'<tr><td>'+esc(r.geoName||"—")+'</td><td>'+esc(r.year||"—")+'</td><td>'+esc(r.month||"—")+'</td><td>'+esc([r.opening,r.mode1,r.mode2].filter(Boolean).join(" · ")||"—")+'</td><td class="num">'+esc(fmt(r.value))+'</td></tr>').join("")}
function download(){const cols=["geoName","year","month","opening","mode1","mode2","value"],lines=[cols.join(","),...state.selected.map(r=>cols.map(c=>'"'+String(r[c]??"").replaceAll('"','""')+'"').join(","))],url=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="ladefe-"+$("board").value+".csv";a.click();URL.revokeObjectURL(url)}
bootstrap().catch(e=>{$("message").hidden=false;$("message").textContent="No se pudo cargar el tablero: "+e.message});
