const state={data:null,rows:[],selected:[]};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const num=v=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("es-AR",{maximumFractionDigits:2}).format(n):v??"—"};
const unique=(rows,key)=>[...new Set(rows.map(r=>String(r[key]??"")).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"es",{numeric:true}));
function fill(select,values,all=false){select.innerHTML=(all?'<option value="">Todos</option>':"")+values.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join("")}
function indicatorName(id){return state.data.indicators.find(x=>String(x.id)===String(id))?.name||id}
function setup(data){state.data=data;$("title").textContent=data.dashboard.name||"Información censal";$("description").textContent=data.dashboard.description||"";$("updated").textContent=data.dashboard.lastDataLoad||"Sin informar";fill($("indicator"),data.indicators.map(x=>x.id));[...$("indicator").options].forEach(o=>o.textContent=indicatorName(o.value));$("indicator").value=data.indicators[0]?.id||"";rebuildFilters();["indicator","type","year"].forEach(id=>$(id).addEventListener("change",()=>id==="indicator"?rebuildFilters():render()));$("reset").onclick=()=>{ $("indicator").selectedIndex=0;rebuildFilters()};$("download").onclick=download;render()}
function base(){const id=$("indicator").value;return state.data.rows.filter(r=>String(r.indicatorId)===id)}
function rebuildFilters(){const rows=base();fill($("type"),unique(rows,"type"),true);fill($("year"),unique(rows,"year").sort((a,b)=>Number(b)-Number(a)),true);render()}
function filtered(){return base().filter(r=>(!$("type").value||String(r.type)===$("type").value)&&(!$("year").value||String(r.year)===$("year").value))}
function render(){const rows=filtered();state.selected=rows;$("message").hidden=true;$("dashboard").hidden=false;$("seriesLabel").textContent=indicatorName($("indicator").value);$("records").textContent=rows.length+" registros visibles";const years=unique(base(),"year").map(Number).filter(Number.isFinite);$("range").textContent=years.length?Math.min(...years)+"–"+Math.max(...years):"—";const latest=$("year").value||String(Math.max(...years));const latestRows=rows.filter(r=>String(r.year)===latest);$("rankingYear").textContent="Año "+latest;$("territories").textContent=unique(latestRows,"geoName").length;const national=latestRows.find(r=>/total|argentina|nacional/i.test((r.geoName||"")+" "+(r.opening1||"")));$("national").textContent=national?num(national.value):"—";$("nationalNote").textContent=national?"Año "+latest:"Sin agregado nacional";drawLine(rows);drawRanking(latestRows);drawTable(rows)}
function series(rows){const m=new Map();rows.forEach(r=>{const y=Number(r.year),v=Number(r.value);if(!Number.isFinite(y)||!Number.isFinite(v))return;const k=y+(r.month?Number(r.month)/12:0);if(!m.has(k))m.set(k,[]);m.get(k).push(v)});return [...m].map(([x,v])=>({x,y:v.reduce((a,b)=>a+b,0)/v.length,label:String(Math.floor(x))})).sort((a,b)=>a.x-b.x)}
function drawLine(rows){const svg=$("lineChart"),pts=series(rows);svg.innerHTML="";if(!pts.length){svg.innerHTML='<text x="380" y="165" text-anchor="middle" class="tick">No hay valores numéricos para graficar</text>';return}const W=760,H=330,p={l:58,r:18,t:20,b:42},xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),sx=x=>p.l+(x-xmin)/(xmax-xmin||1)*(W-p.l-p.r),sy=y=>p.t+(ymax-y)/(ymax-ymin||1)*(H-p.t-p.b);for(let i=0;i<5;i++){const y=p.t+i*(H-p.t-p.b)/4,val=ymax-i*(ymax-ymin)/4;svg.insertAdjacentHTML("beforeend",'<line class="gridline" x1="'+p.l+'" y1="'+y+'" x2="'+(W-p.r)+'" y2="'+y+'"/><text class="tick" x="'+(p.l-8)+'" y="'+(y+4)+'" text-anchor="end">'+esc(num(val))+'</text>')}svg.insertAdjacentHTML("beforeend",'<path class="series" d="'+pts.map((q,i)=>(i?"L":"M")+sx(q.x)+","+sy(q.y)).join(" ")+'"/>');pts.forEach((q,i)=>{svg.insertAdjacentHTML("beforeend",'<circle class="dot" cx="'+sx(q.x)+'" cy="'+sy(q.y)+'" r="4"><title>'+esc(q.label+": "+num(q.y))+'</title></circle>');if(i===0||i===pts.length-1||pts.length<8)svg.insertAdjacentHTML("beforeend",'<text class="tick" x="'+sx(q.x)+'" y="'+(H-15)+'" text-anchor="middle">'+esc(q.label)+'</text>')})}
function drawRanking(rows){const agg=new Map();rows.forEach(r=>{const n=r.geoName||"Sin especificar",v=Number(r.value);if(Number.isFinite(v)){if(!agg.has(n))agg.set(n,[]);agg.get(n).push(v)}});const vals=[...agg].map(([name,v])=>({name,value:v.reduce((a,b)=>a+b,0)/v.length})).sort((a,b)=>b.value-a.value).slice(0,24),max=Math.max(...vals.map(x=>Math.abs(x.value)),1);$("ranking").innerHTML=vals.length?vals.map(x=>'<div class="rank"><span class="rank-name" title="'+esc(x.name)+'">'+esc(x.name)+'</span><span class="bar"><i style="width:'+Math.max(2,Math.abs(x.value)/max*100)+'%"></i></span><span class="rank-value">'+esc(num(x.value))+'</span></div>').join(""):'<p class="message">Sin datos territoriales.</p>'}
function drawTable(rows){$("rows").innerHTML=rows.slice(0,250).map(r=>'<tr><td>'+esc(r.geoName||"—")+'</td><td>'+esc(r.year||"—")+'</td><td>'+esc(r.month||"—")+'</td><td>'+esc([r.opening1,r.opening2].filter(Boolean).join(" · ")||"—")+'</td><td class="num">'+esc(num(r.value))+'</td></tr>').join("")}
function download(){const cols=["geoName","year","month","opening1","opening2","value"],lines=[cols.join(","),...state.selected.map(r=>cols.map(c=>'"'+String(r[c]??"").replaceAll('"','""')+'"').join(","))],url=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="ladefe-censo.csv";a.click();URL.revokeObjectURL(url)}
fetch("data.json").then(r=>{if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}).then(setup).catch(e=>{$("message").textContent="No se pudo cargar el dataset del piloto: "+e.message;$("message").classList.add("error")});