const state={catalog:[],data:null,selected:[],bound:false,geo:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=v=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("es-AR",{maximumFractionDigits:2}).format(n):v??"—"};
const unique=(rows,key)=>[...new Set(rows.map(r=>String(r[key]??"")).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"es",{numeric:true}));
function fill(select,values,all=false){select.innerHTML=(all?'<option value="">Todos</option>':"")+values.map(v=>'<option value="'+esc(v.value??v)+'">'+esc(v.label??v)+'</option>').join("")}
function indicatorName(id){return state.data?.indicators.find(x=>String(x.id)===String(id))?.name||id}
function bind(){if(state.bound)return;state.bound=true;$("board").addEventListener("change",()=>loadBoard($("board").value));$("indicator").addEventListener("change",rebuildFilters);["type","year"].forEach(id=>$(id).addEventListener("change",render));$("reset").onclick=()=>{$("indicator").selectedIndex=0;rebuildFilters()};$("download").onclick=download}
async function bootstrap(){bind();const [r,g]=await Promise.all([fetch("catalog.json"),fetch("provincias.geojson")]);if(!r.ok)throw new Error("HTTP "+r.status);state.catalog=(await r.json()).dashboards;state.geo=g.ok?await g.json():null;fill($("board"),state.catalog.map(x=>({value:x.slug,label:x.name+" · "+x.family})));const requested=new URLSearchParams(location.search).get("tablero"),selected=state.catalog.some(x=>x.slug===requested)?requested:state.catalog[0]?.slug;$("board").value=selected;await loadBoard(selected)}
async function loadBoard(slug){const item=state.catalog.find(x=>x.slug===slug);if(!item)return;$("message").hidden=false;$("message").textContent="Cargando "+item.name+"…";$("dashboard").hidden=true;const r=await fetch(item.data);if(!r.ok)throw new Error("HTTP "+r.status);setup(await r.json());const url=new URL(location.href);url.searchParams.set("tablero",slug);history.replaceState(null,"",url)}
function setup(data){state.data=data;$("title").textContent=data.dashboard.name||"Tablero LADEFE";$("description").textContent=data.dashboard.description||"";$("updated").textContent=(data.dashboard.lastDataLoad||"Sin informar")+" · Familia "+data.family;fill($("indicator"),data.indicators.map(x=>({value:x.id,label:x.name})));rebuildFilters()}
function base(){const id=$("indicator").value;return state.data.rows.filter(r=>String(r.indicatorId)===id)}
function rebuildFilters(){const rows=base();fill($("type"),unique(rows,"type"),true);fill($("year"),unique(rows,"year").sort((a,b)=>Number(b)-Number(a)),true);render()}
function filtered(){return base().filter(r=>(!$("type").value||String(r.type)===$("type").value)&&(!$("year").value||String(r.year)===$("year").value))}
function render(){const rows=filtered();state.selected=rows;$("message").hidden=true;$("dashboard").hidden=false;$("seriesLabel").textContent=indicatorName($("indicator").value);$("records").textContent=rows.length+" registros visibles";const years=unique(base(),"year").map(Number).filter(Number.isFinite);$("range").textContent=years.length?Math.min(...years)+"–"+Math.max(...years):"—";const latest=$("year").value||(years.length?String(Math.max(...years)):"");const latestRows=rows.filter(r=>String(r.year)===latest);$("rankingYear").textContent=latest?"Año "+latest:"";$("territories").textContent=unique(latestRows,"geoName").length;const national=latestRows.find(r=>/total|argentina|nacional|país/i.test((r.geoName||"")+" "+[r.opening,r.mode1,r.mode2].filter(Boolean).join(" ")));$("national").textContent=national?fmt(national.value):"—";$("nationalNote").textContent=national?(national.mode2||national.mode1||"Año "+latest):"Sin agregado nacional";drawLine(rows);drawMap(latestRows);drawRanking(latestRows);drawTable(rows)}
function series(rows){const m=new Map();rows.forEach(r=>{const y=Number(r.year),v=Number(r.value);if(!Number.isFinite(y)||!Number.isFinite(v))return;const k=y+(r.month?Number(r.month)/12:0);if(!m.has(k))m.set(k,[]);m.get(k).push(v)});return[...m].map(([x,v])=>({x,y:v.reduce((a,b)=>a+b,0)/v.length,label:String(Math.floor(x))})).sort((a,b)=>a.x-b.x)}
function drawLine(rows){const svg=$("lineChart"),pts=series(rows);svg.innerHTML="";if(!pts.length){svg.innerHTML='<text x="380" y="165" text-anchor="middle" class="tick">No hay valores numéricos para graficar</text>';return}const W=760,H=330,p={l:58,r:18,t:20,b:42},xs=pts.map(q=>q.x),ys=pts.map(q=>q.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),sx=x=>p.l+(x-xmin)/(xmax-xmin||1)*(W-p.l-p.r),sy=y=>p.t+(ymax-y)/(ymax-ymin||1)*(H-p.t-p.b);for(let i=0;i<5;i++){const y=p.t+i*(H-p.t-p.b)/4,val=ymax-i*(ymax-ymin)/4;svg.insertAdjacentHTML("beforeend",'<line class="gridline" x1="'+p.l+'" y1="'+y+'" x2="'+(W-p.r)+'" y2="'+y+'"/><text class="tick" x="'+(p.l-8)+'" y="'+(y+4)+'" text-anchor="end">'+esc(fmt(val))+'</text>')}svg.insertAdjacentHTML("beforeend",'<path class="series" d="'+pts.map((q,i)=>(i?"L":"M")+sx(q.x)+","+sy(q.y)).join(" ")+'"/>');pts.forEach((q,i)=>{svg.insertAdjacentHTML("beforeend",'<circle class="dot" cx="'+sx(q.x)+'" cy="'+sy(q.y)+'" r="4"><title>'+esc(q.label+": "+fmt(q.y))+'</title></circle>');if(i===0||i===pts.length-1||pts.length<8)svg.insertAdjacentHTML("beforeend",'<text class="tick" x="'+sx(q.x)+'" y="'+(H-15)+'" text-anchor="middle">'+esc(q.label)+'</text>')})}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z]/g,"")}
function provinceKey(v){const n=norm(v);if(n.includes("CIUDADAUTONOMA")||n==="CABA"||n.includes("CAPITALFEDERAL"))return"CABA";if(n.includes("TIERRADELFUEGO"))return"TIERRADELFUEGO";return n.replace(/^PROVINCIADE/,"")}
function featureName(f){const p=f.properties||{};return p.nam||p.nombre||p.NAME_1||p.fna||p.gna||"Provincia"}
function rings(geometry){if(!geometry)return[];if(geometry.type==="Polygon")return geometry.coordinates;if(geometry.type==="MultiPolygon")return geometry.coordinates.flat();return[]}
function drawMap(rows){const svg=$("mapChart");svg.innerHTML="";if(!state.geo){svg.innerHTML='<text x="210" y="235" text-anchor="middle" class="tick">Geometría no disponible</text>';return}const agg=new Map();rows.forEach(r=>{const v=Number(r.value),k=provinceKey(r.geoName);if(Number.isFinite(v)&&k){if(!agg.has(k))agg.set(k,[]);agg.get(k).push(v)}});const values=[...agg.values()].map(a=>a.reduce((x,y)=>x+y,0)/a.length),lo=Math.min(...values),hi=Math.max(...values);const color=v=>{if(!Number.isFinite(v))return"#e6ecef";const t=(v-lo)/(hi-lo||1),a=[217,238,240],b=[0,166,166],c=[11,36,63],mix=(x,y,z)=>Math.round(x+(y-x)*z),rgb=t<.55?a.map((x,i)=>mix(x,b[i],t/.55)):b.map((x,i)=>mix(x,c[i],(t-.55)/.45));return"rgb("+rgb.join(",")+")"};const project=([x,y])=>[(x+74)/21*360+30,(y+21)/-34*430+18];for(const f of state.geo.features||[]){const name=featureName(f),key=provinceKey(name),arr=agg.get(key)||[],value=arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:NaN;let d="";for(const ring of rings(f.geometry)){const points=ring.filter(([x,y])=>x>=-74.5&&x<=-52.5&&y>=-56&&y<=-20).map(project);if(points.length>2)d+=points.map((p,i)=>(i?"L":"M")+p[0].toFixed(1)+","+p[1].toFixed(1)).join("")+"Z"}if(d)svg.insertAdjacentHTML("beforeend",'<path class="province" d="'+d+'" fill="'+color(value)+'"><title>'+esc(name+": "+(Number.isFinite(value)?fmt(value):"sin dato"))+'</title></path>')}if(!values.length)svg.insertAdjacentHTML("beforeend",'<text x="210" y="235" text-anchor="middle" class="tick">Este indicador no tiene desagregación provincial</text>')}
function drawRanking(rows){const agg=new Map();rows.forEach(r=>{const n=r.geoName||"Sin especificar",v=Number(r.value);if(Number.isFinite(v)){if(!agg.has(n))agg.set(n,[]);agg.get(n).push(v)}});const vals=[...agg].map(([name,v])=>({name,value:v.reduce((a,b)=>a+b,0)/v.length})).sort((a,b)=>b.value-a.value).slice(0,24),max=Math.max(...vals.map(x=>Math.abs(x.value)),1);$("ranking").innerHTML=vals.length?vals.map(x=>'<div class="rank"><span class="rank-name" title="'+esc(x.name)+'">'+esc(x.name)+'</span><span class="bar"><i style="width:'+Math.max(2,Math.abs(x.value)/max*100)+'%"></i></span><span class="rank-value">'+esc(fmt(x.value))+'</span></div>').join(""):'<p class="message">Sin datos territoriales.</p>'}
function drawTable(rows){$("rows").innerHTML=rows.slice(0,250).map(r=>'<tr><td>'+esc(r.geoName||"—")+'</td><td>'+esc(r.year||"—")+'</td><td>'+esc(r.month||"—")+'</td><td>'+esc([r.opening,r.mode1,r.mode2].filter(Boolean).join(" · ")||"—")+'</td><td class="num">'+esc(fmt(r.value))+'</td></tr>').join("")}
function download(){const cols=["geoName","year","month","opening","mode1","mode2","value"],lines=[cols.join(","),...state.selected.map(r=>cols.map(c=>'"'+String(r[c]??"").replaceAll('"','""')+'"').join(","))],url=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="ladefe-"+$("board").value+".csv";a.click();URL.revokeObjectURL(url)}
bootstrap().catch(e=>{$("message").hidden=false;$("message").textContent="No se pudo cargar el tablero: "+e.message});
